version: '3'
services:

  consul:
    image: consul:1.15.4
    command: ["agent", "-server", "-bootstrap-expect=1", "-ui", "-client=0.0.0.0"]
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600/udp"
  
  fabio:
    image: fabiolb/fabio
    depends_on:
      - consul
    ports:
      - "9998:9998"
      - "9999:9999"
    volumes:
      - ./fabio.properties:/etc/fabio/fabio.properties

  service_api1:
    build:
      context: ConsulService1/ConsulService1/
      dockerfile: Dockerfile
    depends_on:
      - consul
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_URL=http://0.0.0.0:5001
      - CONSUL_URL=http://host.docker.internal:8500

  service_api2:
    build:
      context: ConsulService1/ConsulService1/
      dockerfile: Dockerfile
    depends_on:
      - consul
    ports:
      - 5002:5002
    environment:
      - ASPNETCORE_URL=http://0.0.0.0:5002
      - CONSUL_URL=http://host.docker.internal:8500

  service_front:
    build:
      context: ConsulService2/ConsulService2/
      dockerfile: Dockerfile
    depends_on:
      - consul
    ports:
      - 6001:6001
    environment:
      - ASPNETCORE_URL=http://0.0.0.0:6001
      - CONSUL_URL=http://host.docker.internal:8500
