FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App

COPY . ./

RUN dotnet restore "ConsulService1/ConsulService1.csproj"
RUN dotnet restore "Core/Core.csproj"

WORKDIR /App/ConsulService1
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App
COPY --from=build-env /App/ConsulService1/out .
EXPOSE 8080
ENTRYPOINT ["dotnet", "ConsulService1.dll"]