FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App

COPY . ./

RUN dotnet restore "ConsulService2/ConsulService2.csproj"
RUN dotnet restore "Core/Core.csproj"

WORKDIR /App/ConsulService2
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App
COPY --from=build-env /App/ConsulService2/out .
EXPOSE 8080
ENTRYPOINT ["dotnet", "ConsulService2.dll"]